name: Terraform Setup State

on:

  workflow_dispatch:

jobs:
  "terraform-create-base-for-tfplan":
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plans/state-cred/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Initialize Terraform
        run: terraform init
      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan -var="subscriptionID=${{secrets.SUBSCRIPTION_ID}}"
      - name: Create or update infrastructure
        run: terraform apply -auto-approve -var="subscriptionID=${{secrets.SUBSCRIPTION_ID}}"
